DROP DATABASE IF EXISTS sampledb;

CREATE DATABASE sampledb DEFAULT CHARACTER SET utf8;
USE sampledb;

CREATE TABLE t_user(
	user_id INT AUTO_INCREMENT PRIMARY KEY,
	user_name VARCHAR(30) NOT NULL DEFAULT "" COMMENT "用户名",
	PASSWORD VARCHAR(32)NOT NULL DEFAULT "" COMMENT "密码",
	last_visit DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT "最后访问时间",
	last_ip VARCHAR(32) NOT NULL DEFAULT "" COMMENT "最后访问的ip"
)ENGINE=INNODB;

CREATE TABLE t_login_log(
	login_log_id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL DEFAULT -1 COMMENT "用户id",
	ip VARCHAR(32) NOT NULL DEFAULT "" COMMENT "最后访问的ip",
	log_datetime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT "最后访问时间"
)ENGINE=INNODB;



INSERT INTO t_user (user_name, PASSWORD) VALUES ('admin', '123456');

SELECT * FROM t_user;